# Generated by Django 5.0.4 on 2024-04-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenclub',
            name='evenement_ptr',
        ),
        migrations.RemoveField(
            model_name='evensocial',
            name='evenement_ptr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='evenclub',
            name='event_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.event'),
        ),
        migrations.AddField(
            model_name='evensocial',
            name='event_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='contactInfo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='intitule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='lieu',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='post_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
    ]
