# Generated by Django 5.0.4 on 2024-04-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_evenclub_evenement_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenclub',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.event'),
        ),
        migrations.AlterField(
            model_name='evensocial',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.event'),
        ),
    ]
